export const FETCH_ZAMATO = 'FETCH_ZAMATO';
export const FETCH_CUISINE_ID = 'FETCH_CUISINE_ID'
export const FETCH_SELECTED_CUISINE = 'FETCH_SELECTED_CUISINE'

export const GET_CURRENT_USER_LOCATION = 'GET_CURRENT_USER_LOCATION'

export const ADD_ADDRESS = 'ADD_ADDRESS';
export const NEW_ADDRESS = 'NEW_ADDRESS';

export const SHOW_CUISINES_MAP = 'SHOW_CUISINES_MAP';

export const SIGN_USER_UP = 'SIGN_USER_UP';

export const GET_ERRORS = 'GET_ERRORS';

export const GET_CITY_CUISINE_ID = 'GET_CITY_CUISINE_ID';

export const FETCH_CUISINE_CITY_ID = 'FETCH_CUISINE_CITY_ID'